#!/bin/bash
set -e

# E2B Sandbox Optimize Pipeline
# Runs accessibility and SEO audits in parallel cloud sandboxes,
# then runs implementation in a third sandbox.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BRANCH_NAME="optimize-e2b-$(date +%Y%m%d-%H%M%S)"
ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================"
echo "E2B Sandbox Optimize Pipeline"
echo "========================================"
echo ""

# Check for required environment variables
if [ -z "$E2B_API_KEY" ]; then
    echo -e "${RED}Error: E2B_API_KEY environment variable is required${NC}"
    echo "Get your API key from https://e2b.dev/dashboard"
    exit 1
fi

# Note: ANTHROPIC_API_KEY not needed - uses local Claude Code Pro

# Check for uncommitted changes
if [ -n "$(git status --porcelain)" ]; then
    echo -e "${YELLOW}Warning: You have uncommitted changes${NC}"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Create optimization branch
echo "Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Ensure dependencies are installed
echo ""
echo "Checking dependencies..."
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# Check if e2b is installed
if ! npm list e2b > /dev/null 2>&1; then
    echo "Installing e2b dependencies..."
    npm install
fi

# Run the TypeScript orchestrator
echo ""
echo "Starting e2b sandbox orchestration..."
echo ""

# Pass through any arguments (like --audit-only)
npx tsx "$PROJECT_DIR/scripts/e2b/orchestrator.ts" "$@"
ORCHESTRATOR_EXIT=$?

if [ $ORCHESTRATOR_EXIT -ne 0 ]; then
    echo ""
    echo -e "${RED}Orchestrator failed with exit code $ORCHESTRATOR_EXIT${NC}"
    echo ""
    read -p "Return to original branch ($ORIGINAL_BRANCH)? [Y/n] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        git checkout "$ORIGINAL_BRANCH"
        git branch -D "$BRANCH_NAME" 2>/dev/null || true
    fi
    exit $ORCHESTRATOR_EXIT
fi

# Check if there are any changes
echo ""
echo "========================================"
echo "Pipeline Complete"
echo "========================================"
echo ""

CHANGES=$(git status --porcelain)

if [ -z "$CHANGES" ]; then
    echo "No changes were made."
    git checkout "$ORIGINAL_BRANCH"
    git branch -D "$BRANCH_NAME" 2>/dev/null || true
    exit 0
fi

# Show what changed
echo -e "${GREEN}Files changed:${NC}"
git status --short
echo ""

# Stage all changes
git add -A

# Show diff summary
echo "Diff summary:"
git diff --cached --stat
echo ""

read -p "Commit these changes? [Y/n] " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    # Create commit
    git commit -m "$(cat <<'EOF'
chore: add audit reports from e2b pipeline

Generated by e2b sandbox parallel audit pipeline:
- axe-core accessibility results
- pa11y accessibility results
- Lighthouse (a11y, SEO, performance) results

Run local Claude to generate remediation specs from these reports.

Co-Authored-By: Claude <noreply@anthropic.com>
EOF
)"

    echo ""
    echo -e "${GREEN}Changes committed to branch: $BRANCH_NAME${NC}"
    echo ""

    # Offer to merge
    read -p "Merge into $ORIGINAL_BRANCH? [y/N] " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git checkout "$ORIGINAL_BRANCH"
        git merge "$BRANCH_NAME" --no-edit
        echo -e "${GREEN}Merged into $ORIGINAL_BRANCH${NC}"

        read -p "Delete optimization branch? [Y/n] " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            git branch -d "$BRANCH_NAME"
        fi
    else
        echo ""
        echo "Branch preserved: $BRANCH_NAME"
        echo "To merge later: git checkout $ORIGINAL_BRANCH && git merge $BRANCH_NAME"
    fi
else
    echo ""
    echo "Changes not committed. Files are staged."
    echo "Branch: $BRANCH_NAME"
    echo ""
    echo "To commit: git commit -m 'your message'"
    echo "To discard: git checkout $ORIGINAL_BRANCH && git branch -D $BRANCH_NAME"
fi
